<?php
/**
 * @copyright Copyright 2008-2009 Cliff Ingham
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
?>
<div>
	<h3>Admin</h3>
	<ul>
		<li><a href="<?php echo BASE_URL; ?>/users">Users</a></li>
		<li><a href="<?php echo BASE_URL; ?>/uploads">Uploads</a></li>
		<li><a href="<?php echo BASE_URL; ?>/media/duplicates.php">Duplicates</a></li>
		<li><a href="<?php echo BASE_URL; ?>/albums">Albums</a></li>
		<li><a href="<?php echo BASE_URL; ?>/rolls">Rolls</a></li>
	</ul>
</div>
